### ISSUE TITLE
 Not working on farsi numbers

### ISSUE THREAD

**Issue by saeidparvizi** [AhmedAlYousif/auto_direction#4]
![WhatsApp Image 2022-01-17 at 09 10 14](https://user-images.githubusercontent.com/34777311/149713932-ba5abc93-b912-4384-afe2-e55c0ca0f7fc.jpeg)

**Comment by AhmedAlYousif** [comment]
I'm not sure what is the issue, the text in the image you provided is RTL as it should.
As far as I know Farsi language is RTL...

**Comment by AhmedAlYousif** [comment]
closed for inactivity
