### ISSUE TITLE
Error: Null check operator used on a null value

### ISSUE THREAD

**Issue by yousifAlneamy** [AhmedAlYousif/auto_direction#5]
Hi, there is a nullable Function `onDirectionChange()?` which causes this error when text direction is called.

It won't take a lot to fix it:

Issue [Linke 39]:
```
(_) => widget.onDirectionChange!(isRTL(widget.text)));
```

Fix:
```
(_) => widget.onDirectionChange?.call(isRTL(widget.text)));
```

**Comment by AhmedAlYousif** [comment]
fixed by the @zvikarp [pull request](https://github.com/AhmedAlYousif/auto_direction/pull/3)
