### ISSUE TITLE
Warning: Operand of null-aware operation '!' has type

### ISSUE THREAD

**Issue by KamalBalah** [AhmedAlYousif/auto_direction#6]
C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/auto_direction-0.0.6/lib/auto_direction.dart:38:22: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance!.addPostFrameCallback(
                     ^

**Comment by AhmedAlYousif** [comment]
the '!' has been removed
